language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phing
